development:
  adapter: mysql2
  database: rampup_development
  username: root
  host: localhost
  port: 3306

test:
  adapter: mysql2
  database: rampup_test
  username: root
  host: localhost
  port: 3306

uat:
  adapter: mysql2
  database: rampup_production
  username: root
  password: PASSWORD
  host: 10.10.1.79
  port: 3306

production:
  adapter: mysql2
  database: rampup_production
  username: root
  password: PASSWORD
  host: 10.10.5.79
  port: 3306